# Generated by Django 4.2.1 on 2023-05-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
    ]
